NER_TAGS = [
    'B-ACCOUNTNAME',
    'B-ACCOUNTNUMBER',
    'B-CREDITCARDNUMBER',
    'B-EMAIL',
    'B-IP',
    'B-IPV4',
    'B-IPV6',
    'B-MAC',
    'B-PASSWORD',
    'B-PHONE_NUMBER',
    'B-SSN',
    'B-USERNAME',
    'I-ACCOUNTNAME',
    'I-ACCOUNTNUMBER',
    'I-CREDITCARDNUMBER',
    'I-EMAIL',
    'I-IP',
    'I-IPV4',
    'I-IPV6',
    'I-MAC',
    'I-PASSWORD',
    'I-PHONE_NUMBER',
    'I-SSN',
    'I-USERNAME',
    'O',
]

NER_TAG_TO_INDEX = {
    'B-ACCOUNTNAME': 0,
    'B-ACCOUNTNUMBER': 1,
    'B-CREDITCARDNUMBER': 2,
    'B-EMAIL': 3,
    'B-IP': 4,
    'B-IPV4': 5,
    'B-IPV6': 6,
    'B-MAC': 7,
    'B-PASSWORD': 8,
    'B-PHONE_NUMBER': 9,
    'B-SSN': 10,
    'B-USERNAME': 11,
    'I-ACCOUNTNAME': 12,
    'I-ACCOUNTNUMBER': 13,
    'I-CREDITCARDNUMBER': 14,
    'I-EMAIL': 15,
    'I-IP': 16,
    'I-IPV4': 17,
    'I-IPV6': 18,
    'I-MAC': 19,
    'I-PASSWORD': 20,
    'I-PHONE_NUMBER': 21,
    'I-SSN': 22,
    'I-USERNAME': 23,
    'O': 24,
    'UNK': 25,  # Adding UNK for unknown tokens
}
INDEX_TO_NER_TAG = {
    0: 'B-ACCOUNTNAME',
    1: 'B-ACCOUNTNUMBER',
    2: 'B-CREDITCARDNUMBER',
    3: 'B-EMAIL',
    4: 'B-IP',
    5: 'B-IPV4',
    6: 'B-IPV6',
    7: 'B-MAC',
    8: 'B-PASSWORD',
    9: 'B-PHONE_NUMBER',
    10: 'B-SSN',
    11: 'B-USERNAME',
    12: 'I-ACCOUNTNAME',
    13: 'I-ACCOUNTNUMBER',
    14: 'I-CREDITCARDNUMBER',
    15: 'I-EMAIL',
    16: 'I-IP',
    17: 'I-IPV4',
    18: 'I-IPV6',
    19: 'I-MAC',
    20: 'I-PASSWORD',
    21: 'I-PHONE_NUMBER',
    22: 'I-SSN',
    23: 'I-USERNAME',
    24: 'O',
    25: 'UNK',  # Adding UNK for unknown tokens
}
